version: 2
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
      # use CircleCI convenience image with pre-installed docker/docker-compose

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build dockers
          command: |
            docker-compose build

      - run:
          name: Run specs
          command: |
            docker-compose up -d fast selenium && docker-compose run --name app-test --service-ports app-test bundle exec rspec spec/features/posts_spec.rb
